language: php

git:
    depth: 1

matrix:
    include:
        - php: 7.1.3
        - php: 7.2

cache:
    directories:
        - var/cache

services:
    - redis-server

before_install:
    - pear config-set preferred_state beta
    - pecl channel-update pecl.php.net
    - yes | pecl install imagick
    - |
      export COMPOSER_UP='composer update --no-progress --no-suggest --ansi'
      export OSF_TESTS='bin/runtests'
      INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
      echo date.timezone = Europe/Paris >> $INI
      echo memory_limit = -1 >> $INI
      echo extension = redis.so >> $INI
      echo extension = imagick.so >> $INI

install:
    - |
      run_tests () {
          set -e
          $COMPOSER_UP && $OSF_TESTS
      }

script:
    - (run_tests)
